### ISSUE TITLE
issue about logs

### ISSUE THREAD

**Issue by ljhhuxiaoba** [YuanchengJiang/GraphGenie#1]
I ran the GraphGenie for 1 hour and then three new log files appeared:
testing.log        bug.log       exception.log
 , could you tell me what the information recorded in these three files is and where the detected bugs can be found?

**Comment by YuanchengJiang** [comment]
Hi @ljhhuxiaoba, detected bugs can be found in bug.log (logic bugs or performance issues) or exception.log (internal errors). testing.log records all executed queries.

**Comment by ljhhuxiaoba** [comment]
Thank for your reply.
