### ISSUE TITLE
Issue when testing AgensGraph

### ISSUE THREAD

**Issue by ljhhuxiaoba** [YuanchengJiang/GraphGenie#2]
I encountered this problem when I followed the instructions to test AgensGraph:

=====GraphGenie=====
Traceback (most recent call last):
  File "E:\Program Files\PythonProjects\GraphGenie-main\main.py", line 323, in <module>
    test = AgensGraphTesting()
  File "E:\Program Files\PythonProjects\GraphGenie-main\main.py", line 279, in __init__
    self.cur.execute("SET graph_path = t")
psycopg2.errors.InvalidParameterValue: invalid value for parameter "graph_path": "t"
DETAIL:  graph "t" does not exist.

Process finished with exit code 1

**Comment by YuanchengJiang** [comment]
Hi, I remember it requires setting up a graph 't' in AgensGraph. You can refer to https://github.com/bitnine-oss/agensgraph-python

**Comment by ljhhuxiaoba** [comment]
Thanks for your reply.
